### ISSUE TITLE
Add description about development mode to the documentation

### ISSUE THREAD

**Issue by tkornut** [IBM/mi-prometheus#35]
TL;DR
when you are developer, call:
python setup.py develop
instead:
python setup.py install

https://setuptools.readthedocs.io/en/latest/setuptools.html#development-mode

**Comment by vmarois** [comment]
+ explain why we are using mocking and the impacts on how to write good docstrings.
i.e. need to have class docstring + MOCK_MODULES + MOCK_CLASSES.
