### ISSUE TITLE
Numpy > 1.11.0 causes errors due to numpy.float64 not being automatically converted to Int

### ISSUE THREAD

**Issue by sesevgen** [IBM/mi-prometheus#69]
**Describe the bug**
Numpy floats do not automatically get converted to Ints when needed with later versions of numpy. Thus, pytorch network configurations that expect Ints throw errors.

**To Reproduce**
Run the following with a later version of numpy installed:
$ mip-offline-trainer --c mi-prometheus/configs/vision/simplecnn_mnist.yaml

**Expected behavior**
Network definitions proceed without errors

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - OS version 18.04
 - Python version 3.5.2
 - PyTorch version 0.4.1

**Comment by vmarois** [comment]
Adressed in #70
