### ISSUE TITLE
Release 0.3.1

### ISSUE THREAD

**Issue by tkornut** [IBM/mi-prometheus#8]
Aggregates issues related to release 0.3.1

**Comment by vmarois** [comment]
*0.3.1 and up*:
- finish refactoring `TextToText` encoder-decoder (secondary)
- EarlyStopping
- `nn.DataParallel` for the models
- Ensure all problems have the fastest implementation of `__getitem__` and `collate_fn` (if not done in *0.2*)
- Continuous integration: have _automated_ unit tests in every problems & models, set up jenkins and GitHub hook
- Have the install scripts working from scratch on several machines types
- Introduce tutorials

*0.4*:
- Timing utility (if not done with `StatisticsAggregator`)
- bAby QA (if not done previously)
- Version 2.0 for data descriptor, not as static (if not done with continuous integration in *0.3*)
- Refactor `utils/GenerateFeatureMaps`, make it more generic


*0.5* ?

*1.0*:
- Full PyTorch 1.0 support
- Documentation accessible on the web (readthedocs.io ?)
